# note: we are only compiling a small number of the possible routines in this 
# directory.   it's usually just a matter of adding the .o here (possibly pulling
# in additional .o dependencies).   we do it conservatively to attempt to minimize
# bad interactions with libpi.
LIB_OBJS = s_cos.o k_cos.o k_sin.o e_rem_pio2.o k_rem_pio2.o s_scalbn.o s_floor.o s_copysign.o s_fabs.o s_sin.o s_atan.o e_atan2.o s_round.o

# k_rem_pio2.o
SRC = $(LIB_OBJS:.o=.c)

ARM = arm-none-eabi
CC = $(ARM)-gcc
LD  = $(ARM)-ld
AS  = $(ARM)-as
OCP = $(ARM)-objcopy


CFLAGS=  -fno-builtin -mhard-float -Og -nostdlib -nostartfiles -ffreestanding  -mcpu=arm1176jzf-s -mtune=arm1176jzf-s -mhard-float -mfpu=vfp -march=armv6zk -std=c99 -Wall -Iinclude -I. -D__BSD_VISIBLE -Wno-implicit-function-declaration

# CFLAGS = -I. -I$(LIBPI) -Wall -Og -std=gnu99 -nostdlib -nostartfiles -ffreestanding  -Werror -fomit-frame-pointer  -Wno-unused-function FPFLAGS = -mhard-float -mcpu=arm1176jzf-s -mtune=arm1176jzf-s -DUSE_FLOAT

all : librpi-m.a 


protos: 
	cproto -I. -Iinclude $(SRC) > math-protos.h

.c.o:
	$(CC) $(CFLAGS) -c $< 

librpi-m.a: $(LIB_OBJS) 
	arm-none-eabi-ar crf librpi-m.a $^ 

clean :
	rm -f $(LIB_OBJS) *~ librpi-m.a  *.o

depend: 
	makedepend -I -Iinclude $(SRC)
# DO NOT DELETE

s_cos.o: cdefs-compat.h math_private.h types-compat.h /usr/include/stdint.h
s_cos.o: /usr/include/features.h /usr/include/stdc-predef.h
s_cos.o: /usr/include/limits.h fpmath.h i386_fpmath.h /usr/include/endian.h
s_cos.o: math_private_openbsd.h
k_cos.o: cdefs-compat.h math_private.h types-compat.h /usr/include/stdint.h
k_cos.o: /usr/include/features.h /usr/include/stdc-predef.h
k_cos.o: /usr/include/limits.h fpmath.h i386_fpmath.h /usr/include/endian.h
k_cos.o: math_private_openbsd.h
k_sin.o: cdefs-compat.h math_private.h types-compat.h /usr/include/stdint.h
k_sin.o: /usr/include/features.h /usr/include/stdc-predef.h
k_sin.o: /usr/include/limits.h fpmath.h i386_fpmath.h /usr/include/endian.h
k_sin.o: math_private_openbsd.h
e_rem_pio2.o: cdefs-compat.h math_private.h types-compat.h
e_rem_pio2.o: /usr/include/stdint.h /usr/include/features.h
e_rem_pio2.o: /usr/include/stdc-predef.h /usr/include/limits.h fpmath.h
e_rem_pio2.o: i386_fpmath.h /usr/include/endian.h math_private_openbsd.h
k_rem_pio2.o: cdefs-compat.h math_private.h types-compat.h
k_rem_pio2.o: /usr/include/stdint.h /usr/include/features.h
k_rem_pio2.o: /usr/include/stdc-predef.h /usr/include/limits.h fpmath.h
k_rem_pio2.o: i386_fpmath.h /usr/include/endian.h math_private_openbsd.h
s_scalbn.o: cdefs-compat.h math_private.h types-compat.h
s_scalbn.o: /usr/include/stdint.h /usr/include/features.h
s_scalbn.o: /usr/include/stdc-predef.h /usr/include/limits.h fpmath.h
s_scalbn.o: i386_fpmath.h /usr/include/endian.h math_private_openbsd.h
s_floor.o: cdefs-compat.h math_private.h types-compat.h /usr/include/stdint.h
s_floor.o: /usr/include/features.h /usr/include/stdc-predef.h
s_floor.o: /usr/include/limits.h fpmath.h i386_fpmath.h /usr/include/endian.h
s_floor.o: math_private_openbsd.h
s_copysign.o: cdefs-compat.h math_private.h types-compat.h
s_copysign.o: /usr/include/stdint.h /usr/include/features.h
s_copysign.o: /usr/include/stdc-predef.h /usr/include/limits.h fpmath.h
s_copysign.o: i386_fpmath.h /usr/include/endian.h math_private_openbsd.h
s_fabs.o: math_private.h cdefs-compat.h types-compat.h /usr/include/stdint.h
s_fabs.o: /usr/include/features.h /usr/include/stdc-predef.h
s_fabs.o: /usr/include/limits.h fpmath.h i386_fpmath.h /usr/include/endian.h
s_fabs.o: math_private_openbsd.h
s_sin.o: cdefs-compat.h math_private.h types-compat.h /usr/include/stdint.h
s_sin.o: /usr/include/features.h /usr/include/stdc-predef.h
s_sin.o: /usr/include/limits.h fpmath.h i386_fpmath.h /usr/include/endian.h
s_sin.o: math_private_openbsd.h
s_atan.o: cdefs-compat.h math_private.h types-compat.h /usr/include/stdint.h
s_atan.o: /usr/include/features.h /usr/include/stdc-predef.h
s_atan.o: /usr/include/limits.h fpmath.h i386_fpmath.h /usr/include/endian.h
s_atan.o: math_private_openbsd.h
e_atan2.o: cdefs-compat.h math_private.h types-compat.h /usr/include/stdint.h
e_atan2.o: /usr/include/features.h /usr/include/stdc-predef.h
e_atan2.o: /usr/include/limits.h fpmath.h i386_fpmath.h /usr/include/endian.h
e_atan2.o: math_private_openbsd.h
