# SUPPORT_OBJS := 

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

# uncomment if you want it to automatically run.
RUN=1

TEST_SRC := 2-bug-self-modify.c

TEST_SRC := 0-ident-dcg.c
TEST_SRC := 1-self-modifying.c
TEST_SRC := 4-derive-pc-reg.c

# to run all the tests.
# TEST_SRC := $(wildcard ./[0-9]*.c)

include $(CS240LX_2022_PATH)/libpi/mk/Makefile.template


