PROG_SRC = check-timings.c
SRC = fake-pi.c  fake-random.c  pi-random.c

PI_DIR = ../my-install
CFLAGS = -I../code.staff -DLIBPI_FAKE
RUN = 1

# LIBS = -lutil
include $(CS240LX_2022_PATH)/libunix/mk/Makefile.unix
