# SUPPORT_OBJS := 

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

# uncomment if you want it to automatically run.
RUN=1

TEST_SRC := jit-code.c

# to run all the tests.

include $(CS240LX_2022_PATH)/libpi/mk/Makefile.template


