TEST_SRC = main.c

# make a local copy of cstart so you can modify it.
SUPPORT_OBJS = interrupts-asm.o interrupts-c.o timer-interrupt.o


# define this if you need to give the device for your pi
TTYUSB = 

# set RUN = 1 if you want the code to automatically run after building.
RUN = 1


DEPS = ./Makefile
include $(CS240LX_2022_PATH)/libpi/mk/Makefile.template
